name: Generated APK

env:
  # The name of the main module repository
  main_project_module: app

on:
  push:
    branches: [ release ]

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set timezone
        uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Create APK Release
      - name: Build ${{ github.repository }} - ${{ env.main_project_module }}
        env:
          REPO: ${{ github.repository }}
          BUILD_TIME: ${{ env.build_time }}
          ALIAS: ${{ secrets.ALIAS }}  # TVBoxOSC
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }} # TVBoxOSC
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }} # TVBoxOSC
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > ./TVBoxOSC.jks
          echo "build_time=$(date +'%Y%m%d_%H%M')" >> $GITHUB_ENV
          chmod +x ./gradlew
          ./gradlew clean
          echo "${{ env.build_time }}"
          ./gradlew assembleRelease  --build-cache --parallel --daemon --warning-mode all

      - name: Release - ${{ env.build_time }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.build_time }}
          body: ${{ github.event.head_commit.message }}
          tag_name: ${{ env.build_time }}
          files: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk

