name: Generated APK

env:
  # The name of the main module repository
  main_project_module: app

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to Release
        required: true

jobs:
  build:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > ./keystore.jks

      # Create APK Release
      - name: Build ${{ github.repository }} - ${{ env.main_project_module }} - ${{ env.date_today }} - ${{ github.event.inputs.tag }}
        env:
          REPO: ${{ github.repository }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease  --build-cache --parallel --daemon --warning-mode all

      - name: Release - ${{ steps.tag.outputs.tag }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.date_today }}
          body: ${{ github.event.head_commit.message }}
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk

